# Generated by Django 5.0.14 on 2026-03-20 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("phone", models.CharField(db_index=True, max_length=20, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "customers",
            },
        ),
        migrations.CreateModel(
            name="Style",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("vibe", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("image_url", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "styles",
            },
        ),
        migrations.CreateModel(
            name="CaptureRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_path", models.CharField(max_length=500)),
                ("processed_path", models.CharField(max_length=500)),
                ("filename", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(db_index=True, default="PENDING", max_length=50),
                ),
                ("face_count", models.IntegerField(blank=True, null=True)),
                ("error_note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="captures",
                        to="mirrai_app.customer",
                    ),
                ),
            ],
            options={
                "db_table": "capture_records",
            },
        ),
        migrations.CreateModel(
            name="FaceAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("face_shape", models.CharField(blank=True, max_length=50, null=True)),
                ("golden_ratio_score", models.FloatField(blank=True, null=True)),
                ("image_url", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_analyses",
                        to="mirrai_app.customer",
                    ),
                ),
            ],
            options={
                "db_table": "face_analyses",
            },
        ),
        migrations.CreateModel(
            name="ConsultationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_data_snapshot", models.JSONField(blank=True, null=True)),
                ("status", models.CharField(default="SENT", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="mirrai_app.customer",
                    ),
                ),
                (
                    "selected_style",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mirrai_app.style",
                    ),
                ),
            ],
            options={
                "db_table": "consultation_requests",
            },
        ),
        migrations.CreateModel(
            name="StyleSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("style_id", models.IntegerField()),
                ("match_score", models.FloatField(blank=True, null=True)),
                ("is_sent_to_designer", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style_selections",
                        to="mirrai_app.customer",
                    ),
                ),
            ],
            options={
                "db_table": "style_selections",
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_length", models.CharField(max_length=50)),
                ("target_vibe", models.CharField(max_length=50)),
                ("scalp_type", models.CharField(max_length=50)),
                ("hair_colour", models.CharField(max_length=50)),
                ("budget_range", models.CharField(max_length=50)),
                ("preference_vector", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey",
                        to="mirrai_app.customer",
                    ),
                ),
            ],
            options={
                "db_table": "surveys",
            },
        ),
    ]
