# Generated by Django 5.0.14 on 2026-03-20 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mirrai_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormerRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.UUIDField(db_index=True)),
                (
                    "source",
                    models.CharField(db_index=True, default="generated", max_length=20),
                ),
                ("style_id_snapshot", models.IntegerField(db_index=True)),
                ("style_name_snapshot", models.CharField(max_length=100)),
                ("style_description_snapshot", models.TextField(blank=True, null=True)),
                ("keywords", models.JSONField(blank=True, default=list)),
                (
                    "sample_image_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "simulation_image_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("llm_explanation", models.TextField(blank=True, null=True)),
                ("match_score", models.FloatField(blank=True, null=True)),
                ("rank", models.PositiveSmallIntegerField(default=1)),
                ("is_chosen", models.BooleanField(db_index=True, default=False)),
                ("chosen_at", models.DateTimeField(blank=True, null=True)),
                ("is_sent_to_admin", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "capture_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="former_recommendations",
                        to="mirrai_app.capturerecord",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="former_recommendations",
                        to="mirrai_app.customer",
                    ),
                ),
                (
                    "style",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="former_recommendations",
                        to="mirrai_app.style",
                    ),
                ),
            ],
            options={
                "db_table": "former_recommendations",
                "ordering": ["rank", "-created_at"],
            },
        ),
    ]
