# Generated by Django 5.0.14 on 2026-03-20 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mirrai_app", "0002_formerrecommendation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("store_name", models.CharField(max_length=100)),
                ("role", models.CharField(default="owner", max_length=20)),
                ("phone", models.CharField(db_index=True, max_length=20, unique=True)),
                (
                    "business_number",
                    models.CharField(db_index=True, max_length=30, unique=True),
                ),
                ("password_hash", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "partners",
            },
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="selected_recommendation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consultations",
                to="mirrai_app.formerrecommendation",
            ),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="source",
            field=models.CharField(default="current_recommendations", max_length=30),
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="survey_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="styleselection",
            name="selected_recommendation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="style_selections",
                to="mirrai_app.formerrecommendation",
            ),
        ),
        migrations.AddField(
            model_name="styleselection",
            name="source",
            field=models.CharField(default="current_recommendations", max_length=30),
        ),
        migrations.AddField(
            model_name="styleselection",
            name="survey_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="consultationrequest",
            name="status",
            field=models.CharField(default="PENDING", max_length=20),
        ),
        migrations.CreateModel(
            name="CustomerSessionNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="mirrai_app.consultationrequest",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_notes",
                        to="mirrai_app.customer",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_notes",
                        to="mirrai_app.partner",
                    ),
                ),
            ],
            options={
                "db_table": "customer_session_notes",
            },
        ),
        migrations.AddField(
            model_name="consultationrequest",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consultations",
                to="mirrai_app.partner",
            ),
        ),
    ]
