# Generated by Django 5.0.14 on 2026-03-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mirrai_app", "0011_admin_terminology_alignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminaccount",
            name="business_verification_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="adminaccount",
            name="business_verification_status",
            field=models.CharField(default="checksum_only", max_length=30),
        ),
        migrations.AddField(
            model_name="client",
            name="image_storage_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="client",
            name="image_storage_consented_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
